language: node_js
node_js:
  - "8.9.1"
before_script:
  - npm install -g tslint
  - npm install -g nodemon
  - npm install -g ts-node
deploy:
  provider: heroku
  api_key:
    secure: "dbaf1dc8-4cbd-48af-ba22-63a91742a2f8"
  app: typenode
  strategy: git
  run:
    - "npm start"