language: node_js
node_js:
  - "8.9.1"
cache:
  directories:
    - "node_modules"
deploy:
  provider: heroku
  api_key:
    secure: "dbaf1dc8-4cbd-48af-ba22-63a91742a2f8"
  app: typenode
  strategy: git
before_install:
  - npm install -g nodemon
  - npm install -g ts-node
  - npm install -g tslint
before_script:
  - npm run lint
before_deploy:
  - npm run build